### ISSUE TITLE
AddContactDialogFragment

### ISSUE THREAD

**Issue by wing-tree** [5oreo5/ContactApp#41]
- 크기 구하는게 상당히 인상적이네요! 꽤 까다로웠을텐데 잘하셨어요!

https://github.com/5oreo5/ContactApp/blob/7b81abbd7a57d205bc28b1003a8a24ed94202018/app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt#L26

**Comment by minji-0420** [comment]
앗....그것은 용현튜터님이 도와주셨습니다 ㅎㅎ...
